version: 2
project_name: teldrive
env:
  - GO111MODULE=on

before:
  hooks:
  - task ui
  - task gen
  
builds:
  - env:
      - CGO_ENABLED=0
      
    main: main.go
    flags: -trimpath
    ldflags:
     - -extldflags=-static
     - -s -w
     - -X {{ .ModulePath }}/internal/version.Version={{ .Version }}
     - -X {{ .ModulePath }}/internal/version.CommitSHA={{ .ShortCommit }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  
archives:
  - name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README*.md
      - LICENSE
dockers:
  - image_templates:
      - "ghcr.io/tgdrive/{{ .ProjectName }}:{{ .Tag }}-amd64"
    use: buildx
    dockerfile: goreleaser.dockerfile
    build_flag_templates:
    - "--platform=linux/amd64"

  - image_templates:
      - "ghcr.io/tgdrive/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "ghcr.io/tgdrive/{{ .ProjectName }}:latest"
    use: buildx
    dockerfile: goreleaser.dockerfile
    goarch: arm64
    build_flag_templates:
    - --platform=linux/arm64/v8

docker_manifests:
  - name_template: "ghcr.io/tgdrive/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/tgdrive/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/tgdrive/{{ .ProjectName }}:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/tgdrive/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/tgdrive/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/tgdrive/{{ .ProjectName }}:{{ .Tag }}-arm64"
      
changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Refactoring
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 3
  filters:
    exclude:
      - '^README'
      - '^Update'
      - '^Version'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  draft: true